---
version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - ./codebuild/.env
  web:
    build: ./codebuild
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./blankslate:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./codebuild/.env
