# Generated by Django 5.0 on 2023-12-27 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_remove_word_response_word_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 14, 47, 56, 631636)),
        ),
    ]
