# Generated by Django 5.0 on 2023-12-27 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 14, 51, 3, 472050, tzinfo=datetime.timezone.utc)),
        ),
    ]
