# Generated by Django 5.0 on 2023-12-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_remove_word_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='fix',
            field=models.CharField(choices=[('prefix', 'Prefix'), ('suffix', 'Suffix')], default='prefix', max_length=6),
        ),
    ]
